---
- name: Create group account for tomcat
  group:
    name: "{{tomcat_group}}"
    state: present

- name: Create user account for tomcat
  user:
    name: "{{tomcat_user}}"
    comment: Tomcat
    group: "{{tomcat_group}}"
    state: present
    shell: /sbin/nologin
    home: "{{tomcat_basedir}}"
    createhome: no

- name: Modify limits.conf on nofile
  pam_limits:
    domain: "{{tomcat_user}}"
    limit_type: "{{ item }}"
    limit_item: nofile
    value: "{{tomcat_nofile_limit}}"
  with_items:
   - hard
   - soft      

- name: Modify limits.conf on stack
  pam_limits:
    domain: "{{tomcat_user}}"
    limit_type: "{{ item }}"
    limit_item: stack
    value: "{{tomcat_stack_limit}}"
  with_items:
    - hard
    - soft

- name: Create dirs of /opt and /var/cache/ansible
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /opt
    - /var/cache/ansible

- name: Get stats of tomcat tarball
  stat:
    path: "/var/cache/ansible/{{tomcat_pkg_name}}-{{tomcat_version}}.tar.gz"
    get_md5: no
    get_checksum: no
  register: st_tomcat_tarball

- name: Gets the tarball
  get_url:
    url: "{{tomcat_repo_url}}/v{{tomcat_version}}/bin/{{tomcat_pkg_name}}-{{tomcat_version}}.tar.gz"
    dest: /var/cache/ansible/
  when: not st_tomcat_tarball.stat.exists
  register: new_archive_tomcat

- name: Get stats of /opt/tomcat
  stat:
    path: "/opt/{{tomcat_pkg_name}}-{{tomcat_version}}"
    get_md5: no
    get_checksum: no
  register: st_tomcat

- name: Unarchive source
  unarchive:
    src: "/var/cache/ansible/{{tomcat_pkg_name}}-{{tomcat_version}}.tar.gz"
    dest: /opt
    remote_src: yes
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  when: new_archive_tomcat is changed or not st_tomcat.stat.exists

- name: reset ownership
  file:
    dest: "/opt/{{tomcat_pkg_name}}-{{tomcat_version}}"
    recurse: yes
    owner: "{{tomcat_user}}"
    group: "{{tomcat_group}}"
  changed_when: False

- name: Create symlink of /opt/tomcat
  file:
    src: "/opt/{{tomcat_pkg_name}}-{{tomcat_version}}"
    dest: /opt/tomcat
    state: link

- include: selinux.yml
  when: ansible_distribution in ['RedHat', 'CentOS']
