---
- name: Set seboolean
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Set permissive on tomcat
  selinux_permissive:
    name: tomcat_t
    permissive: true
  when: tomcat_se_mode == 'permissive'
