---
- name: Set seboolean for httpd
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Set seboolean for tomcat
  seboolean:
    name: tomcat_can_network_connect_db
    state: yes
    persistent: yes
  failed_when: False
